### ISSUE TITLE
As a user I want to see a Project Page

### ISSUE THREAD

**Issue by dmaslan** [StudioCompanion/companion-studio#28]
## 🚀 Feature Proposal

A Page consisting of:

- Project Title
- [ ] https://github.com/StudioCompanion/companion-studio/issues/22
- [ ] https://github.com/StudioCompanion/companion-studio/issues/24
- Combination of:
  - [ ] https://github.com/StudioCompanion/companion-studio/issues/26 
  - [ ] https://github.com/StudioCompanion/companion-studio/issues/25
  - [ ] https://github.com/StudioCompanion/companion-studio/issues/23 
  - [ ] https://github.com/StudioCompanion/companion-studio/issues/27
